### ISSUE TITLE
Please release this as an Elm package

### ISSUE THREAD

**Issue by alex-damian-negru** [calions-app/jsonapi-http#2]
## Description

I've noticed that `https://github.com/calions-app/jsonapi-http` is no longer available, probably due to an username change. This causes the following error when trying to build an app:

```
I downloaded the source code for calions-app/jsonapi-http 1.3.0 from:

    https://github.com/calions-app/jsonapi-http/zipball/1.3.0/

But it looks like the hash of the archive has changed since publication:

  Expected: 0c81af15eb8ed482feac239d366b4bd67d3dee12
    Actual: 5bdd7dd8a4bc5f23536bdc7fd91e1ea620f3a438

This usually means that the package author moved the version tag, so report it
to them and see if that is the issue. Folks on Elm slack can probably help as
well.
```

Elm packages still seems to list the [package under the old username](https://package.elm-lang.org/packages/calions-app/jsonapi-http/latest/), which does not work.

## Solution

The above being said, would you please release the repo as a package under the new username `FabienHenon/jsonapi-http`? :)

**Comment by FabienHenon** [comment]
Hi,

Yes sorry, I’ll do that this evening. Sorry for the inconvenience 

Best regards 

Fabien Henon

**Comment by cazacutudor** [comment]
We are facing the same issue, restoring the old package or releasing a new one will be fantastic, thanks @FabienHenon :heart:

**Comment by FabienHenon** [comment]
The package has been moved to `https://package.elm-lang.org/packages/FabienHenon/jsonapi-http/latest/`. Sorry for the delay
